# Generated by Django 2.2.12 on 2021-03-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
    ]
