# Generated by Django 2.2.12 on 2021-04-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210403_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_name',
            field=models.CharField(default=1, max_length=50, verbose_name='first_name'),
            preserve_default=False,
        ),
    ]
