# Generated by Django 2.2.12 on 2021-03-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(default=1, upload_to='images', verbose_name='photo'),
            preserve_default=False,
        ),
    ]
