# Generated by Django 2.2.12 on 2021-04-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
    ]
