# Generated by Django 2.2.12 on 2021-03-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
