# Generated by Django 3.1.7 on 2021-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210328_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
