# Generated by Django 2.2.19 on 2021-04-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210410_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.IntegerField(default=0),
        ),
    ]
