# Generated by Django 2.2.19 on 2021-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
