# Generated by Django 2.1.7 on 2021-04-02 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210402_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
